x-airbyte-logging: &airbyte-default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file

services:
  airbyte-init:
    image: airbyte/init:${AIRBYTE_VERSION}
    container_name: ${AIRBYTE_HOST_NAME}-init
    logging: *airbyte-default-logging
    command: /bin/sh -c "./scripts/create_mount_directories.sh /local_parent ${AIRBYTE_HACK_LOCAL_ROOT_PARENT} ${AIRBYTE_LOCAL_ROOT}"
    environment:
      - LOCAL_ROOT=${AIRBYTE_LOCAL_ROOT}
      - HACK_LOCAL_ROOT_PARENT=${AIRBYTE_HACK_LOCAL_ROOT_PARENT}
  
  airbyte-bootloader:
    image: airbyte/bootloader:${AIRBYTE_VERSION}
    container_name: ${AIRBYTE_HOST_NAME}-bootloader
    logging: *airbyte-default-logging
    environment:
      - AIRBYTE_VERSION=${AIRBYTE_VERSION}
      - DATABASE_USER=${AIRBYTE_DATABASE_USER}
      - DATABASE_PASSWORD=${AIRBYTE_DATABASE_PASSWORD}
      - DATABASE_URL=${AIRBYTE_DATABASE_URL}
      - LOG_LEVEL=${AIRBYTE_LOG_LEVEL}

  airbyte-worker:
    image: airbyte/worker:${AIRBYTE_VERSION}
    container_name: ${AIRBYTE_HOST_NAME}-worker
    logging: *airbyte-default-logging
    environment:
      - AIRBYTE_VERSION=${AIRBYTE_VERSION}
      - DATABASE_USER=${AIRBYTE_DATABASE_USER}
      - DATABASE_PASSWORD=${AIRBYTE_DATABASE_PASSWORD}
      - DATABASE_URL=${AIRBYTE_DATABASE_URL}
      - CONFIG_DATABASE_USER=${AIRBYTE_CONFIG_DATABASE_USER:-}
      - CONFIG_DATABASE_PASSWORD=${AIRBYTE_CONFIG_DATABASE_PASSWORD:-}
      - CONFIG_DATABASE_URL=${AIRBYTE_CONFIG_DATABASE_URL:-}
      - AUTO_DISABLE_FAILING_CONNECTIONS=${AIRBYTE_AUTO_DISABLE_FAILING_CONNECTIONS}
      - CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=${AIRBYTE_CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION:-}
      - CONFIG_ROOT=${AIRBYTE_CONFIG_ROOT}
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE}
      - INTERNAL_API_HOST=${AIRBYTE_INTERNAL_API_HOST}
      - JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=${AIRBYTE_JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION:-}
      - JOB_MAIN_CONTAINER_CPU_LIMIT=${AIRBYTE_JOB_MAIN_CONTAINER_CPU_LIMIT}
      - JOB_MAIN_CONTAINER_CPU_REQUEST=${AIRBYTE_JOB_MAIN_CONTAINER_CPU_REQUEST}
      - JOB_MAIN_CONTAINER_MEMORY_LIMIT=${AIRBYTE_JOB_MAIN_CONTAINER_MEMORY_LIMIT}
      - JOB_MAIN_CONTAINER_MEMORY_REQUEST=${AIRBYTE_NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST}
      - LOCAL_DOCKER_MOUNT=${AIRBYTE_LOCAL_DOCKER_MOUNT}
      - LOCAL_ROOT=${AIRBYTE_LOCAL_ROOT}
      - LOG_LEVEL=${AIRBYTE_LOG_LEVEL}
      - LOG_CONNECTOR_MESSAGES=${LOG_CONNECTOR_MESSAGES}
      - MAX_CHECK_WORKERS=${AIRBYTE_MAX_CHECK_WORKERS}
      - MAX_DISCOVER_WORKERS=${AIRBYTE_MAX_DISCOVER_WORKERS}
      - MAX_SPEC_WORKERS=${AIRBYTE_MAX_SPEC_WORKERS}
      - MAX_SYNC_WORKERS=${AIRBYTE_MAX_SYNC_WORKERS}
      - MAX_NOTIFY_WORKERS=${AIRBYTE_MAX_NOTIFY_WORKERS}
      - SHOULD_RUN_NOTIFY_WORKFLOW=${AIRBYTE_SHOULD_RUN_NOTIFY_WORKFLOW}
      - NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_LIMIT=${AIRBYTE_NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_LIMIT}
      - NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST=${AIRBYTE_NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST}
      - NORMALIZATION_JOB_MAIN_CONTAINER_CPU_LIMIT=${AIRBYTE_NORMALIZATION_JOB_MAIN_CONTAINER_CPU_LIMIT}
      - NORMALIZATION_JOB_MAIN_CONTAINER_CPU_REQUEST=${AIRBYTE_NORMALIZATION_JOB_MAIN_CONTAINER_CPU_REQUEST}
      - SECRET_PERSISTENCE=${SECRET_PERSISTENCE}
      - SYNC_JOB_MAX_ATTEMPTS=${AIRBYTE_SYNC_JOB_MAX_ATTEMPTS}
      - SYNC_JOB_MAX_TIMEOUT_DAYS=${AIRBYTE_SYNC_JOB_MAX_TIMEOUT_DAYS}
      - TEMPORAL_HOST=${AIRBYTE_TEMPORAL_HOST}
      - TRACKING_STRATEGY=${AIRBYTE_TRACKING_STRATEGY}
      - WEBAPP_URL=${AIRBYTE_WEBAPP_URL}
      - WORKSPACE_DOCKER_MOUNT=${AIRBYTE_WORKSPACE_DOCKER_MOUNT}
      - WORKSPACE_ROOT=${AIRBYTE_WORKSPACE_ROOT}
      - METRIC_CLIENT=${AIRBYTE_METRIC_CLIENT}
      - OTEL_COLLECTOR_ENDPOINT=${AIRBYTE_OTEL_COLLECTOR_ENDPOINT}
      - JOB_ERROR_REPORTING_STRATEGY=${AIRBYTE_JOB_ERROR_REPORTING_STRATEGY}
      - JOB_ERROR_REPORTING_SENTRY_DSN=${JOB_ERROR_REPORTING_SENTRY_DSN}
      - ACTIVITY_MAX_ATTEMPT=${AIRBYTE_ACTIVITY_MAX_ATTEMPT}
      - ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS=${AIRBYTE_ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS}
      - ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS=${AIRBYTE_ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS}
      - WORKFLOW_FAILURE_RESTART_DELAY_SECONDS=${AIRBYTE_WORKFLOW_FAILURE_RESTART_DELAY_SECONDS}
      - AUTO_DETECT_SCHEMA=${AIRBYTE_AUTO_DETECT_SCHEMA}
      - USE_STREAM_CAPABLE_STATE=${AIRBYTE_USE_STREAM_CAPABLE_STATE}
      - MICRONAUT_ENVIRONMENTS=${AIRBYTE_WORKERS_MICRONAUT_ENVIRONMENTS}
      - APPLY_FIELD_SELECTION=${APPLY_FIELD_SELECTION}
      - FIELD_SELECTION_WORKSPACES=${FIELD_SELECTION_WORKSPACES}
    configs:
      - flags
    depends_on:
      airbyte-bootloader:
        condition: service_completed_successfully

  airbyte-server:
    image: airbyte/server:${AIRBYTE_VERSION}
    logging: *airbyte-default-logging
    container_name: ${AIRBYTE_HOST_NAME}-server
    environment:
      - AIRBYTE_ROLE=${AIRBYTE_ROLE:-}
      - AIRBYTE_VERSION=${AIRBYTE_VERSION}
      - DATABASE_USER=${AIRBYTE_DATABASE_USER}
      - DATABASE_PASSWORD=${AIRBYTE_DATABASE_PASSWORD}
      - DATABASE_URL=${AIRBYTE_DATABASE_URL}
      - CONFIG_DATABASE_USER=${AIRBYTE_CONFIG_DATABASE_USER:-}
      - CONFIG_DATABASE_PASSWORD=${AIRBYTE_CONFIG_DATABASE_PASSWORD:-}
      - CONFIG_DATABASE_URL=${AIRBYTE_CONFIG_DATABASE_URL:-}
      - CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=${AIRBYTE_CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION:-}
      - CONFIG_ROOT=${AIRBYTE_CONFIG_ROOT}
      - JOB_MAIN_CONTAINER_CPU_LIMIT=${AIRBYTE_JOB_MAIN_CONTAINER_CPU_LIMIT}
      - JOB_MAIN_CONTAINER_CPU_REQUEST=${AIRBYTE_JOB_MAIN_CONTAINER_CPU_REQUEST}
      - JOB_MAIN_CONTAINER_MEMORY_LIMIT=${AIRBYTE_JOB_MAIN_CONTAINER_MEMORY_LIMIT}
      - JOB_MAIN_CONTAINER_MEMORY_REQUEST=${AIRBYTE_JOB_MAIN_CONTAINER_MEMORY_REQUEST}
      - JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=${AIRBYTE_JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION:-}
      - LOG_LEVEL=${AIRBYTE_LOG_LEVEL}
      - NEW_SCHEDULER=${NEW_SCHEDULER}
      - SECRET_PERSISTENCE=${SECRET_PERSISTENCE}
      - TEMPORAL_HOST=${AIRBYTE_TEMPORAL_HOST}
      - TRACKING_STRATEGY=${AIRBYTE_TRACKING_STRATEGY}
      - JOB_ERROR_REPORTING_STRATEGY=${AIRBYTE_JOB_ERROR_REPORTING_STRATEGY}
      - JOB_ERROR_REPORTING_SENTRY_DSN=${JOB_ERROR_REPORTING_SENTRY_DSN}
      - WEBAPP_URL=${AIRBYTE_WEBAPP_URL}
      - WORKER_ENVIRONMENT=${WORKER_ENVIRONMENT}
      - WORKSPACE_ROOT=${AIRBYTE_WORKSPACE_ROOT}
      - GITHUB_STORE_BRANCH=${GITHUB_STORE_BRANCH}
      - MICRONAUT_ENVIRONMENTS=${AIRBYTE_WORKERS_MICRONAUT_ENVIRONMENTS}
      - AUTO_DETECT_SCHEMA=${AIRBYTE_AUTO_DETECT_SCHEMA}
    configs:
      - flags
    depends_on:
      airbyte-bootloader:
        condition: service_completed_successfully

  airbyte-temporal:
    image: airbyte/temporal:${AIRBYTE_VERSION}
    logging: *airbyte-default-logging
    container_name: ${AIRBYTE_HOST_NAME}-temporal
    environment:
      - DB=postgresql
      - DB_PORT=${AIRBYTE_DATABASE_PORT}
      - POSTGRES_PWD=${AIRBYTE_DATABASE_PASSWORD}
      - POSTGRES_SEEDS=${AIRBYTE_DATABASE_HOST}
      - POSTGRES_USER=${AIRBYTE_DATABASE_USER}
      - LOG_LEVEL=${AIRBYTE_LOG_LEVEL}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml

  airbyte-cron:
    image: airbyte/cron:${AIRBYTE_VERSION}
    logging: *airbyte-default-logging
    container_name: ${AIRBYTE_HOST_NAME}-cron
    environment:
      - AIRBYTE_VERSION=${AIRBYTE_VERSION}
      - DATABASE_USER=${AIRBYTE_DATABASE_USER}
      - DATABASE_PASSWORD=${AIRBYTE_DATABASE_PASSWORD}
      - DATABASE_URL=${AIRBYTE_DATABASE_URL}
      - CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=${AIRBYTE_CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION}
      - LOG_LEVEL=${AIRBYTE_LOG_LEVEL}
      - WORKSPACE_ROOT=${AIRBYTE_WORKSPACE_ROOT}
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE}
      - MICRONAUT_ENVIRONMENTS=${AIRBYTE_CRON_MICRONAUT_ENVIRONMENTS}
      - REMOTE_CONNECTOR_CATALOG_URL=${REMOTE_CONNECTOR_CATALOG_URL}
      - TEMPORAL_HISTORY_RETENTION_IN_DAYS=${TEMPORAL_HISTORY_RETENTION_IN_DAYS}
      - UPDATE_DEFINITIONS_CRON_ENABLED=${UPDATE_DEFINITIONS_CRON_ENABLED}
    configs:
      - flags
    depends_on:
      airbyte-bootloader:
        condition: service_completed_successfully
      airbyte-temporal:
        condition: service_started

  airbyte-connector-builder-server:
    image: airbyte/connector-builder-server:${AIRBYTE_VERSION}
    logging: *airbyte-default-logging
    container_name: ${AIRBYTE_HOST_NAME}-connector-builder-server
    environment:
      - AIRBYTE_VERSION=${AIRBYTE_VERSION}
    depends_on:
      airbyte-bootloader:
        condition: service_completed_successfully

  airbyte-webapp:
    image: airbyte/webapp:${AIRBYTE_VERSION}
    logging: *airbyte-default-logging
    container_name: ${AIRBYTE_HOST_NAME}-webapp
    environment:
      - AIRBYTE_ROLE=${AIRBYTE_ROLE:-}
      - AIRBYTE_VERSION=${AIRBYTE_VERSION}
      - API_URL=${AIRBYTE_API_URL:-}
      - CONNECTOR_BUILDER_API_URL=${AIRBYTE_CONNECTOR_BUILDER_API_URL:-}
      - INTERNAL_API_HOST=${AIRBYTE_INTERNAL_API_HOST}
      - CONNECTOR_BUILDER_API_HOST=${AIRBYTE_CONNECTOR_BUILDER_API_HOST}
      - TRACKING_STRATEGY=${AIRBYTE_TRACKING_STRATEGY}
      - OPENREPLAY=${OPENREPLAY:-}
      - PAPERCUPS_STORYTIME=${PAPERCUPS_STORYTIME:-}
    depends_on:
      airbyte-bootloader:
        condition: service_completed_successfully

  airbyte-proxy:
    image: airbyte/proxy:${AIRBYTE_VERSION}
    container_name: ${AIRBYTE_HOST_NAME}-proxy
    environment:
      - BASIC_AUTH_USERNAME=${AIRBYTE_BASIC_AUTH_USERNAME}
      - BASIC_AUTH_PASSWORD=${AIRBYTE_BASIC_AUTH_PASSWORD}
      - BASIC_AUTH_PROXY_TIMEOUT=${AIRBYTE_BASIC_AUTH_PROXY_TIMEOUT}
    depends_on:
      airbyte-webapp:
        condition: service_started
      airbyte-server:
        condition: service_started
