#
base: &base
  image: chatwoot/chatwoot:${CHATWOOT_VERSION}
  environment:
    NODE_ENV: production
    RAILS_ENV: production
    INSTALLATION_ENV: docker
    FRONTEND_URL: ${CHATWOOT_FRONTEND_URL}
    SECRET_KEY_BASE: ${CHATWOOT_SECRET_KEY_BASE}
    POSTGRES_HOST: ${CHATWOOT_POSTGRES_HOST}
    POSTGRES_PORT: ${CHATWOOT_POSTGRES_PORT}
    POSTGRES_DATABASE: ${CHATWOOT_POSTGRES_DATABASE}
    POSTGRES_USERNAME: ${CHATWOOT_POSTGRES_USERNAME}
    POSTGRES_PASSWORD: ${CHATWOOT_POSTGRES_PASSWORD}
    REDIS_URL: ${CHATWOOT_REDIS_URL}
    REDIS_PASSWORD: ${CHATWOOT_REDIS_PASSWORD}

services:
  rails-migrate:
    <<: *base
    container_name: chatwoot-migrate
    command: ['bundle', 'exec', 'rails', 'db:chatwoot_prepare']

  rails:
    <<: *base
    container_name: chatwoot
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    container_name: chatwoot-worker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
