#
name: minio

networks:
  minio:
    external: true
    name: minio_local

volumes:
  minio:
    name: minio_data

services:
  minio:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - 9090:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER # s3 key
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD # s3 secret
    networks:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio:/data
