#
name: postgres

networks:
  postgres:
    external: true
    name: postgres_local

volumes:
  postgres:
    name: postgres_data
  pgadmin:
    name: pgadmin_data

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - postgres
    ports:
      - 5432:5432
    deploy:
      restart_policy:
        condition: none

  pgAdmin:
    image: dpage/pgadmin4:7.7
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    ports:
      - 8001:80 # LOCALHOST_PORT:CONTAINER_PORT
    deploy:
      restart_policy:
        condition: none
