#
name: redis

networks:
  redis:
    external: true
    name: redis_external

volumes:
  redis:
    name: redis_data

services:
  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - redis:/data
    networks:
      - redis
    ports:
      - 6399:6379
    deploy:
      restart_policy:
        condition: on-failure
